---
name:   Behavior Demo               # The application display name
short:  Btree                       # A shortened name for reference
appid:  edu.cornell.gdiac.btree     # Application identifier for Mac, iOS, Android
suffix: true

build:  build                       # The build directory (targets are each a subdirectory)
assets: assets                      # The folder with the game assets (do not list asset)
icon:   icon.png

orientation: landscape              # The orientation for mobile devices

sources:                            # The list of the source code files
    - source/*.cpp
    - source/*.h

modules:
    - scene2
    
# This must be one of portrait, landscape, portrait-flipped, landscape-flipped,
targets:                            # The target platforms to build for
    - android                       # Android Studio
    - apple                         # XCode (note macOS and iOS use one project)
    - windows                       # Windows Sisual Studio
    - cmake                         # This supports all Desktop platfor G8AB3BC G9E187A GEE0AE4 G982BBE4