---
name: Glitchblade # The application display name
short: GB # A shortened name for reference
appid: edu.cornell.gdiac.glitchblade # Application identifier for Mac, iOS, Android
suffix: GE19D122

build: build # The build directory (targets are each a subdirectory)
assets: assets # The folder with the game assets (do not list asset)
icon: icon.png

orientation: landscape # The orientation for mobile devices

sources: # The list of the source code files
  - source/*.cpp
  - source/*.h
  - source/app/*.cpp
  - source/app/*.h
  - source/core/*.cpp
  - source/core/*.h

  - source/enemies/*.cpp
  - source/enemies/*.h
  - source/enemies/actionmodel_variants/*.cpp
  - source/enemies/actionmodel_variants/*.h
  - source/enemies/enemy_variants/*.cpp
  - source/enemies/enemy_variants/*.h

  - source/game/*.cpp
  - source/game/*.h
  - source/game/ui/*.cpp
  - source/game/ui/*.h
  - source/game/objects/*.cpp
  - source/game/objects/*.h

  - source/levels/*.cpp
  - source/levels/*.h

  - source/player/*.cpp
  - source/player/*.h

modules:
  - audio # We need sound
  - physics2 # We need the physics libraries
  - scene2 # We want the 2d UI

targets: # The target platforms to build for
  - android     # Android Studio
  - apple       # XCode (note macOS and iOS use one project)
  - windows     # Windows Visual Studio
  - cmake       # Generic desktop builds